import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'edge';

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const file = formData.get('file') as File | null;
    
    if (!file) {
      return NextResponse.json({ error: 'No file provided' }, { status: 400 });
    }

    // Mock processing delay (3 seconds) to pretend we're calling ConvertAPI
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    // Create a mock docx file content
    const mockContent = new TextEncoder().encode("This is a mock converted Word (.docx) document generated by PDF Pocket Server Mock.");
    
    const fileName = file.name.replace(/\.pdf$/i, '') + '.docx';
    
    return new NextResponse(mockContent, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${fileName}"`,
      },
    });
  } catch (error) {
    return NextResponse.json({ error: 'Processing failed' }, { status: 500 });
  }
}
